version: '3.8'

services:
  creator-studio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: creator_desktop_studio
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
